name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create Tag
      run: |
        git tag $(date +'%Y%m%d%H%M%S') -a -m "Generated tag from GitHub Action"
        git push --tags

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $(date +'%Y%m%d%H%M%S')
        release_name: Release $(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false